<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnEnter</name>
   <tag></tag>
   <elementGuidId>0d2e6034-50fd-4a1f-b216-cb1f81254e9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/ion-nav-view/div/div[2]/div[2]/div/form/input[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/ion-nav-view/div/div[2]/div[2]/div/form/input[2]</value>
   </webElementProperties>
</WebElementEntity>
