<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnLoginErestoSales</name>
   <tag></tag>
   <elementGuidId>6eb10114-fd3e-4a41-8ad5-d99c6057f90e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/ion-nav-view/div/div[2]/div[2]/div/form[2]/input[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/ion-nav-view/div/div[2]/div[2]/div/form[2]/input[3]</value>
   </webElementProperties>
</WebElementEntity>
