<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fieldEmailErestoSales</name>
   <tag></tag>
   <elementGuidId>5955fbac-a942-478f-b8e0-7341d79f7659</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/ion-nav-view/div/div[2]/div[2]/div/form[2]/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/ion-nav-view/div/div[2]/div[2]/div/form[2]/input[1]</value>
   </webElementProperties>
</WebElementEntity>
