<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tableD4</name>
   <tag></tag>
   <elementGuidId>b8061a30-8f57-4c29-bb05-4c954489655c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;table-view-container&quot;]/div[1]/div[2]/div[2]/div[2]/div[4]/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;table-view-container&quot;]/div[1]/div[2]/div[2]/div[2]/div[4]/h3</value>
   </webElementProperties>
</WebElementEntity>
