<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnPOS</name>
   <tag></tag>
   <elementGuidId>fe9f31b6-e7fa-4f0d-9028-169f228b09cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/div[3]/div[2]/a[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div[1]/div[3]/div[2]/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div[1]/div[3]/div[2]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
